# Project information
site_name: Digital Tabletop
site_description: Digital table top gaming
site_author: Joseph Samela
site_url: https://josephsamela.github.io/digital-tabletop

# Page tree
# nav:
#   - Material: index.md
#   - Getting started: getting-started.md
#   - Extensions:
#     - Admonition: extensions/admonition.md
#     - CodeHilite: extensions/codehilite.md
#     - Footnotes: extensions/footnotes.md
#     - Metadata: extensions/metadata.md
#     - Permalinks: extensions/permalinks.md
#     - PyMdown: extensions/pymdown.md
#   - Specimen: specimen.md
#   - Customization: customization.md
#   - Compliance with GDPR: compliance.md
#   - Release notes: release-notes.md
#   - Author's notes: authors-notes.md
#   - Contributing: contributing.md
#   - License: license.md
nav:
    - Welcome: index.md
    - Introduction: intro.md
    - About: about.md
    - Classes:
        - User: classes/user.md
        - Database: classes/db.md
        - Auth: classes/auth.md
        - Game: classes/game.md
    - Tests:
        - User: tests/test_module_user.md
        - Database: tests/test_module_db.md
        - Auth: tests/test_module_auth.md
        - Game: tests/test_module_game.md

# Customization
theme: 
    name: material
    feature:
        tabs: true

extra:
  social:
    - type: globe
      link: http://josephsamela.github.io
    - type: github-alt
      link: https://github.com/josephsamela
    - type: twitter
      link: https://twitter.com/josephsamela

# Repository
repo_name: josephsamela/digital-tabletop
repo_url: https://github.com/josephsamela/digital-tabletop
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2017 - 2019 Joseph Samela'

# Don't include MkDocs' JavaScript
include_search_page: false
search_index_only: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

